# Site settings
title: Gameefy
description: Fun Learning
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gameefy.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gameefy
user_description: We build games and apps, especially those that help ease learning process with fun and exciment!
user_title: learn the fun way
email: gameefy@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
